### ISSUE TITLE
Plugin Manager cannot find file

### ISSUE THREAD

**Issue by MajusCorp** [justanotherfoundry/freemix-glyphsapp#10]
Glyphs Plugin Manager says the file "Anchors.glyphsPalette" doesn't exist.

**Comment by justanotherfoundry** [comment]
This is a known issue.

Right now, the only solution from by side would be to place the plug-in into its own repository, which I am not willing to do.

**Comment by MajusCorp** [comment]
Thanks Tim. Manual install it is; done.
