### ISSUE TITLE
Install from Plugin Manager not working

### ISSUE THREAD

**Issue by kontur** [justanotherfoundry/freemix-glyphsapp#11]
When I open the Plugin Manager and try to install `AnchorsPalette/Anchors` (which links to this repo) I get an error: 

> The file “Anchors.glyphsPalette” doesn’t exist.

**Comment by justanotherfoundry** [comment]
This is a known issue.

Right now, the only solution from by side would be to place the plug-in into its own repository, which I am not willing to do.
