### ISSUE TITLE
OrageBackground plugin in not needed any more

### ISSUE THREAD

**Issue by schriftgestalt** [justanotherfoundry/freemix-glyphsapp#15]
There are options to change the color of the outlines in the background in preferences, now.

**Comment by justanotherfoundry** [comment]
Oh, excellent! I guess it is a good sign if one of my Plug-ins is becoming obsolete.

Would it be possible to set the (foreground and background) stroke thickness as well? I find the lines far too thin as they are now. This is why my plug-in makes them thicker, and this is why I will probably keep using it.

Also, what is the meaning of the second “Background stroke color” selection in the preferences?

**Comment by schriftgestalt** [comment]
the second color is used when you enable an other layer by clicking the eye in the layer panel.

**Comment by schriftgestalt** [comment]
And now you can enable nodes in the background, too.
