### ISSUE TITLE
Delete All Hints to check corners/caps

### ISSUE THREAD

**Issue by Tosche** [justanotherfoundry/freemix-glyphsapp#16]
Since corner and cap components are implemented as hints, Delete All Hints script deletes them as well. It needs to evaluate each and every hint and check hint.isCorner before deleting.

**Comment by justanotherfoundry** [comment]
Good point. Will have a look.

**Comment by justanotherfoundry** [comment]
Fixed!
https://github.com/justanotherfoundry/freemix-glyphsapp/commit/8a2132d13e6951fcb3d2a58052419e1209398efe
