### ISSUE TITLE
Anchors Palette: traceback

### ISSUE THREAD

**Issue by mekkablue** [justanotherfoundry/freemix-glyphsapp#17]
Just received this via support.

```
Details:
Traceback (most recent call last):

 File "GlyphsApp/GlyphsApp/__init__.py", line 1055, in callback

 File "~/Library/Application Support/Glyphs/Plugins/Anchors.glyphsPalette/Contents/Resources/plugin.py", line 77, in update
   if self.font.selectedLayers:

AttributeError: 'NoneType' object has no attribute 'selectedLayers'

App:2.5.1-1141 Plugin:1.0-1.0
```

**Comment by justanotherfoundry** [comment]
Thanks, I will have a look at this.
My first guess is that the None is a line break in the edit window. I never understood why line breaks are returned as pseudo glyphs through the API.

**Comment by mekkablue** [comment]
I know it can be tricky. But it can be useful to find the lines that are entered, or create line breaks yourself when you change the content of the Edit view. I am using them in the [Lines by Masters](https://github.com/mekkablue/Glyphs-Scripts/blob/master/Masters/Lines%20by%20Master.py) script, for instance. And in the _Show Mark Preview_ plug-in.

**Comment by justanotherfoundry** [comment]
Seems this [has been fixed](https://github.com/justanotherfoundry/freemix-glyphsapp/commit/c0a9ad0d90c5cf16b216c6311878a2dafd3c1296#diff-5b79b894591857dd9a79d0db2f7a277a).
