### ISSUE TITLE
Panel never gets smaller after a glyph with a lot anchors

### ISSUE THREAD

**Issue by schriftgestalt** [justanotherfoundry/freemix-glyphsapp#19]
after this glyph:
<img width="176" alt="Screenshot" src="https://user-images.githubusercontent.com/174660/67616894-e991f280-f7dd-11e9-98b9-acb92d1dd963.png">
it stays big like this
<img width="179" alt="Screenshot" src="https://user-images.githubusercontent.com/174660/67616923-062e2a80-f7de-11e9-94c1-902c5c7aa743.png">
As glyphs with more then four anchors are rare, it should still go back to the default state. The annoyance from the movement is less then the wasted space in the sidebar.

**Comment by justanotherfoundry** [comment]
> The annoyance from the movement is less then the wasted space in the sidebar.

Sorry, I disagree.

Also, you can always collapse the panel to save space. And if you un-collapse, it gets back to 4 lines default height. You need to trigger an update in-between, not sure how to improve that.
