### ISSUE TITLE
computing bounds

### ISSUE THREAD

**Issue by schriftgestalt** [justanotherfoundry/freemix-glyphsapp#21]
https://github.com/justanotherfoundry/freemix-glyphsapp/blob/9d8e808b158f624401e6b36e5d356df7a00344be/AlignmentPalette/Alignment.glyphsPalette/Contents/Resources/plugin.py#L59

Why is that a bad thing?

And this code is missing components.

**Comment by justanotherfoundry** [comment]
> Why is that a bad thing?

I want exact information about the contours as they are. In case I have fractional co-ordinates but a font grid of 1 (which is possible), I still want to see the actual (fractional) positions of the contour.

If STICK_TO_GRID is False then this is particularly relevant.

Glyphs allows fractional co-ordinates even when the grid is 1. If we don’t consider this a bug we should consider it a feature, and build everything else accordingly.

**Comment by justanotherfoundry** [comment]
> And this code is missing components.
Can you elaborate?

**Comment by schriftgestalt** [comment]
You are right. I missed the "decomposeLayer" part.
