### ISSUE TITLE
Mask to Master not working with G3

### ISSUE THREAD

**Issue by sebsan** [justanotherfoundry/freemix-glyphsapp#27]
Hi! Great scripts, I almost can't live without them and sadly can't make Mask to Master work in Glyphs 3

**Comment by justanotherfoundry** [comment]
Can you try uninstalling and re-installing _Mask to Master_? Florian fixed a Glyphs 3/Python 3 problem yesterday (https://github.com/justanotherfoundry/freemix-glyphsapp/commit/d606b74150f41d0bba5c8eb5906d695882d72c33) so it may be working already (I haven’t tested).

**Comment by florianpircher** [comment]
The change from https://github.com/justanotherfoundry/freemix-glyphsapp/commit/d606b74150f41d0bba5c8eb5906d695882d72c33 allows the script to be loaded into Glyphs 3, although it still does not work for me when components are in the background.

I was able to fix the script for background-components which in turn do not contain any components with the this change: https://github.com/florianpircher/freemix-glyphsapp/commit/9f2972fb2098245559d056cce00e1da2405c163e. If I can figure out background-components which contain other components I will propose a pull-request.

I’m new to the Glyphs API, so maybe I am missing something obvious.

**Comment by sebsan** [comment]
Mask to Master works fine now.
There still seems to be an issue with Insert Glyph to Background

**Comment by florianpircher** [comment]
With the release of Glyphs 3043 (cutting edge, soon stable) this issue is resolved.

`GSLayer.decomposeComponents` [works again like in Glyphs 2](https://forum.glyphsapp.com/t/gslayer-decomposecomponents-is-not-recursive/16775) which fixes the nested-components not decomposing recursively.

**Comment by justanotherfoundry** [comment]
Excellent! Thanks for the notification.

That means I can take that while loop out of the RMX code as well.
