### ISSUE TITLE
checking for empty paths. 

### ISSUE THREAD

**Issue by schriftgestalt** [justanotherfoundry/freemix-glyphsapp#37]
https://github.com/justanotherfoundry/freemix-glyphsapp/blob/ca4060a668faaf8bb114e71682858743fe299ad4/AlignmentPalette/Alignment.glyphsPalette/Contents/Resources/plugin.py#L62

I got a crash report that looks like was caused by a path without any nodes.

**Comment by justanotherfoundry** [comment]
Ah, thanks! Just wondering: How can there be a path without nodes?

**Comment by schriftgestalt** [comment]
That shouldn’t happen but sometimes one sneaks in. e.g. when a script is not paying attentions.

**Comment by schriftgestalt** [comment]
the internal API is not failing in such a case but we added a exception to the python API as that is what python would do.

**Comment by justanotherfoundry** [comment]
Fixed: https://github.com/justanotherfoundry/freemix-glyphsapp/commit/dd5e99b
