### ISSUE TITLE
Symmetrify script but for selected?

### ISSUE THREAD

**Issue by weiweihuanghuang** [justanotherfoundry/freemix-glyphsapp#4]
Would it be possible to make a script that is similar to the symmetrify script but instead lets you select a set of paths and replicate it in the symmetrify schemes? For example select a quadrant of a circle and create a circle (H), or half an italic circle and create a full circle (S) and so on.

**Comment by justanotherfoundry** [comment]
Interesting idea. I'll think about it but for now, I don't see enough practical application.
