### ISSUE TITLE
Remove Backup Layers.py incompatible with Smart Components

### ISSUE THREAD

**Issue by danielgamage** [justanotherfoundry/freemix-glyphsapp#6]
smart components use layers with maximum and minimum values (respectively) to interpolate between https://glyphsapp.com/tutorials/smart-components

i haven't dug into the glyphs api to figure out the best way to exempt those specific layers from this script, but one solution might be to only run the script on _selected_ glyphs rather than all the glyphs in the file.

**Comment by justanotherfoundry** [comment]
Thanks for the feedback, Daniel. I just tweaked the script so that it only applies to selected glyphs. I also fixed the handling of brace layers. Will have a look at smart components.

**Comment by danielgamage** [comment]
Great, thanks for looking at that! That solution you went with makes the script usable for files with smart components, so whether you tweak it further or not, you've addressed my issue :smile:
